#!/bin/bash
# English Teacher App - Configuration Checklist
# Copiez cette checklist et suivez chaque étape

echo "================================================"
echo "✅ English Teacher App - Setup Checklist"
echo "================================================"
echo ""
echo "Suivez ces étapes pour lancer votre application:"
echo ""

# STEP 1
echo "📋 ÉTAPE 1: Créer un compte Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Allez sur https://supabase.com"
echo "☐ Cliquez 'Sign Up'"
echo "☐ Créez un compte (email + mot de passe)"
echo "☐ Confirmez votre email"
echo ""

# STEP 2
echo "📋 ÉTAPE 2: Créer un projet Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Cliquez 'New project'"
echo "☐ Nom: 'english-teacher' (ou votre choix)"
echo "☐ Région: us-east-1 (ou proche de vous)"
echo "☐ Mot de passe BD: (généré automatiquement, gardez-le)"
echo "☐ Attendez que le projet soit créé (~5 min)"
echo ""

# STEP 3
echo "📋 ÉTAPE 3: Copier les clés Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Dans Supabase, cliquez 'Settings' (⚙️)"
echo "☐ Cliquez 'API'"
echo "☐ Copiez 'Project URL' → Sauvegardez quelque part"
echo "☐ Copiez 'anon public key' → Sauvegardez quelque part"
echo ""

# STEP 4
echo "📋 ÉTAPE 4: Configurer les variables d'environnement"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Ouvrez le fichier: /Users/mac/Documents/english-teacher-app/.env.local"
echo "☐ Remplacez NEXT_PUBLIC_SUPABASE_URL par votre Project URL"
echo "☐ Remplacez NEXT_PUBLIC_SUPABASE_ANON_KEY par votre anon key"
echo "☐ Sauvegardez le fichier (Cmd+S)"
echo ""

# STEP 5
echo "📋 ÉTAPE 5: Configurer la base de données"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Retournez dans Supabase"
echo "☐ Cliquez 'SQL Editor' (icône >_)"
echo "☐ Cliquez '+ New query'"
echo "☐ Ouvrez: /Users/mac/Documents/english-teacher-app/docs/DATABASE_SETUP.sql"
echo "☐ Copiez TOUT le contenu"
echo "☐ Collez dans l'éditeur SQL Supabase"
echo "☐ Cliquez 'Run' (flèche verte)"
echo "☐ Vérifiez qu'il n'y a pas d'erreurs"
echo ""

# STEP 6
echo "📋 ÉTAPE 6: Lancer l'application"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Ouvrez un terminal"
echo "☐ Tapez: cd /Users/mac/Documents/english-teacher-app"
echo "☐ Tapez: npm run dev"
echo "☐ Attendez 'Ready in 4.1s'"
echo "☐ Ouvrez http://localhost:3000 dans votre navigateur"
echo ""

# STEP 7
echo "📋 ÉTAPE 7: Tester l'authentification"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Vous êtes sur http://localhost:3000"
echo "☐ Cliquez 'S'inscrire'"
echo "☐ Remplissez le formulaire:"
echo "     - Nom: Votre nom"
echo "     - Email: votre-email@example.com"
echo "     - Mot de passe: Au moins 6 caractères"
echo "☐ Cliquez 'S'inscrire'"
echo "☐ Vous devriez voir 'Inscription réussie!'"
echo "☐ Cliquez 'Se connecter'"
echo "☐ Utilisez votre email et mot de passe"
echo "☐ Vous voyez le 'Tableau de bord' ✓"
echo ""

# STEP 8
echo "📋 ÉTAPE 8: Ajouter des données d'exemple (optionnel)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Retournez dans Supabase SQL Editor"
echo "☐ Cliquez '+ New query'"
echo "☐ Ouvrez: /Users/mac/Documents/english-teacher-app/docs/SAMPLE_DATA.sql"
echo "☐ Copiez et collez le contenu"
echo "☐ Cliquez 'Run'"
echo "☐ Retournez dans l'app → Cliquez 'Leçons'"
echo "☐ Vous devriez voir les leçons d'exemple! ✓"
echo ""

# FINAL
echo "================================================"
echo "🎉 FÉLICITATIONS!"
echo "================================================"
echo "Votre application est maintenant fonctionnelle!"
echo ""
echo "Prochaines étapes:"
echo "  1. Ajouter plus de leçons et vocabulaire"
echo "  2. Tester avec des utilisateurs réels"
echo "  3. Déployer sur Vercel (gratuit)"
echo ""
echo "📚 Lisez la documentation:"
echo "  - QUICKSTART.md    (Guide de démarrage)"
echo "  - README.md        (Documentation complète)"
echo "  - COMMANDS.md      (Toutes les commandes)"
echo ""
echo "🆘 Problèmes?"
echo "  - Vérifiez .env.local"
echo "  - Redémarrez npm run dev"
echo "  - Consultez QUICKSTART.md"
echo ""
echo "================================================"
echo ""
